base_url = "https://rafaellehmkuhl.github.io/"

title = "Home"
description = "My name is Rafael Araujo Lehmkuhl and I'm a mechanical engineer who codes."

compile_sass = true
highlight_code = false
build_search_index = false
theme = "hyde"

[extra]

hyde_links = [
    { name = "E-Mail", url = "mailto:rafael.lehmkuhl93@gmail.com"},
    { name = "GitHub", url = "https://github.com/rafaellehmkuhl"},
]

hyde_theme = "theme-base-00"